# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Configuration for the shell process job.

---
dontChroot: false
timeout: 10
script:
    - "TARGET=$(ls @@ROOT@@/etc/mkinitcpio.d/linux*.preset 2>/dev/null | head -1); if [ -n \"$TARGET\" ]; then mv -v @@ROOT@@/etc/mkinitcpio.d/pear \"$TARGET\"; else mv -v @@ROOT@@/etc/mkinitcpio.d/pear @@ROOT@@/etc/mkinitcpio.d/linux.preset; fi"
  
