#Arch-Linux-GUI Calamares settings configuration file

 # Configuration file for Calamares
# Syntax is YAML 1.2
---

modules-search: [ local ]

instances:
- id:       ask-install-type
  module:   shellprocess
  config:   shellprocess-ask-install-type.conf
- id:       algmkinitcpio
  module:   shellprocess
  config:   shellprocess-alg-mkinitcpio.conf
- id:       mkinitcpio-optional
  module:   shellprocess
  config:   shellprocess-mkinitcpio-optional.conf
- id:       copy-netinstall-url
  module:   shellprocess
  config:   shellprocess-copy-netinstall-url.conf
- id:       netinstall
  module:   shellprocess
  config:   shellprocess-netinstall.conf
- id:       remove-livecd
  module:   shellprocess
  config:   shellprocess-remove-livecd.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - shellprocess@ask-install-type
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - luksopenswaphookcfg
  - shellprocess@algmkinitcpio
  - initcpiocfg
  - shellprocess@mkinitcpio-optional
  - removeuser
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - shellprocess@copy-netinstall-url
  - shellprocess@netinstall
  - packages
  - grubcfg
  - shellprocess@remove-livecd
  - bootloader
  - umount
- show:
  - finished


branding: pear

prompt-install: false

dont-chroot: false

disable-cancel: false

disable-cancel-during-exec: false
